kind: Service
apiVersion: v1
metadata:
  name: articulate-frontend
spec:
  selector:
    app: articulate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: articulate
spec:
  selector:
      matchLabels:
        app: articulate
  replicas: 3
  template:
    metadata:
      labels:
        app: articulate
    spec:
      containers:
        - name: articulate
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
      imagePullSecrets:
        - name: myregistrykey