kind: Service
apiVersion: v1
metadata:
  name: articulate-frontend
spec:
  selector:
    app: articulate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: articulate
spec:
  selector:
      matchLabels:
        app: articulate
  replicas: 2
  template:
    metadata:
      labels:
        app: articulate
      name: articulate
    spec:
      containers:
        - name: articulate
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 0.2
          ports:
            - containerPort: 8082
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: articulatehpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: articulate
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20