apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
kind: Service
apiVersion: v1
metadata:
  name: articulate-frontend
  namespace: kube-system
spec:
  selector:
    app: articulate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: articulated
  namespace: kube-system
spec:
  selector:
      matchLabels:
        app: articulate
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: articulate
    spec:
      containers:
        - name: articulate
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
          ports:
            - containerPort: 8082
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: articulatehpa
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: articulated
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10