server:
  port: 8082
  
logging:
  level:
    io:
      pivotal: INFO

spring:
  application:
    name: articulate

articulate:
  attendee-service:
    uri: http://localhost:8181



management:
  security:
    enabled: false
  cloudfoundry:
    skip-ssl-validation: true
